author: Liam Rahav & Luke LaScala
copyright: © 2016 Liam Rahav & Luke LaScala All Rights Reserved
min_acl: private
skip_undocumented: true
github_url: https://github.com/LiamRahav/ultimate-tic-tac-toe
hide_documentation_coverage: true

custom_categories:
  - name: Game Models
    children:
    - BattleGround
    - Grid
    - Tile
    - TileProtocol
    - QueryItemRepresentable
  - name: Message Logic
    children:
    - MSMessageTemplateLayout

